#region * * * P L E A S E   D O   N O T   M O D I F Y * * *
/***************************************************************************
** Module name   : Exxlib.cs
** Description   : Client Stub File for .NET (9.12.0.0)
**
**                 * * *  P L E A S E   D O   N O T   M O D I F Y  * * *
**
** Author        : Generated by Software AG EntireX IDL Compiler
** Template      : csharp_client.tpl for C#
** Platform      : .NET-able Platforms
** Usage         : <use wizard>
***************************************************************************/
#endregion
#region parameters
/**************************************************************************
** sanitize C#
** Broker       : localhost:1971
** Service      : RPC/NATSRV2800/CALLNAT
** ATOSTRING       : Default
** A1TOCHAR        : false
** B1TOBYTE        : false
** TRIM            : true
** SANITIZE        : true
***************************************************************************/
#endregion
#region required namespaces
using System;
using System.Text;
using System.Runtime.InteropServices;
using SoftwareAG.EntireX.NETWrapper.Runtime;
#endregion

#region AssemblyInfo
#if USE_ASSEMBLY_INFO
using System.Reflection ;
[assembly: AssemblyTitle("EntireX .NET Wrapper Client")]
[assembly: AssemblyDescription("EntireX .NET Wrapper Client")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Software AG")]
[assembly: AssemblyProduct("EntireX Communicator")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyKeyFile("")]
[assembly: AssemblyKeyName("")]
#endif
#endregion

namespace SoftwareAG.EntireX.NETWrapper.Generated.EXXLIB
{
  [EntireXVersion("9.12.0.0")]
  [Library("EXXLIB")]
  [Broker("ias-dev:6500")]
  [Service("RPC/SRV224/CALLNAT")]
  public class Exxlib : ServiceHolder
  {
#region 	Constructor(s) etc for LIBRARY 'EXXLIB'

    public Exxlib() : base() {}
    public Exxlib(Broker broker) : base ( broker ) {}
    public Exxlib(Service service) : base ( service ) {}

#endregion
#region Method/Function for LIBRARY 'EXXLIB' PROGRAM 'MBRSRV'

    [Program("MBRSRV")]
    public void Mbrsrv(
      [SendAs(IdlType.AV, Length=0d, Trim=true)][In]  string functionName,
      [SendAs(IdlType.AV, Length=0d, Trim=true)][In]  string inputData,
      [SendAs(IdlType.AV, Length=0d, Trim=true)][Out] out StringBuilder responseData
    ){
      responseData = new StringBuilder() ;
      service.Send(
        this.GetType().GetMethod("Mbrsrv"),
        functionName,
        inputData,
        responseData
      );
    }

#endregion
  }
}

